<?php
/**
 * Plugin Name: WP Telegram Bot Connector
 * Plugin URI: https://example.com/
 * Description: Control center for your external Node.js Telegram bot. Enter your Bot URL, Username, and application passwords to connect. Provides post history automatically generated by the Bot.
 * Version: 1.1.0
 * Author: Your Name
 * License: GPL v2 or later
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Register meta key so the WP REST API accepts and utilizes "_created_by_bot" during POST /wp-json/wp/v2/posts overrides!
add_action('init', 'wp_bot_register_meta');
function wp_bot_register_meta() {
    register_post_meta('post', '_created_by_bot', array(
        'show_in_rest' => true,
        'single' => true,
        'type' => 'boolean',
    ));
}

add_action('admin_menu', 'wp_bot_admin_menu');
function wp_bot_admin_menu() {
    add_menu_page('Telegram Bot Settings', 'Telegram Bot', 'manage_options', 'wp-bot-connector', 'wp_bot_settings_page', 'dashicons-smartphone', 30);
}

function wp_bot_settings_page() {
    // Handle form submission
    if (isset($_POST['wp_bot_submit'])) {
        check_admin_referer('wp_bot_settings_verify');
        
        $node_url = sanitize_text_field($_POST['node_url']);
        $bot_username = sanitize_text_field($_POST['bot_username']);
        $bot_password = sanitize_text_field($_POST['bot_password']);
        
        update_option('wp_bot_node_url', $node_url);
        update_option('wp_bot_username', $bot_username);
        update_option('wp_bot_password', $bot_password);
        
        $wp_url = site_url();
        
        $response = wp_remote_post(rtrim($node_url, '/') . '/api/configure', array(
            'body' => json_encode(array(
                'wpUrl' => $wp_url,
                'username' => $bot_username,
                'password' => $bot_password
            )),
            'headers' => array('Content-Type' => 'application/json'),
            'timeout' => 15
        ));

        if (is_wp_error($response)) {
            echo '<div class="notice notice-error is-dismissible"><p>Failed to connect to Node.js: ' . esc_html($response->get_error_message()) . '</p></div>';
        } else {
            $body = wp_remote_retrieve_body($response);
            $data = json_decode($body, true);
            if (!empty($data['success'])) {
                echo '<div class="notice notice-success is-dismissible"><p>Successfully connected to the Node.js Telegram Bot Framework!</p></div>';
            } else {
                echo '<div class="notice notice-error is-dismissible"><p>Node.js rejected the connection: ' . esc_html($body) . '</p></div>';
            }
        }
    }

    $node_url = get_option('wp_bot_node_url', 'http://localhost:3000');
    $bot_username = get_option('wp_bot_username', '');
    $bot_password = get_option('wp_bot_password', '');
    ?>
    <div class="wrap">
        <h1>Telegram Bot Connector</h1>
        
        <form method="POST">
            <?php wp_nonce_field('wp_bot_settings_verify'); ?>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="node_url">Node.js Bot Server URL</label></th>
                    <td>
                        <input name="node_url" type="text" id="node_url" value="<?php echo esc_attr($node_url); ?>" class="regular-text" required placeholder="e.g. http://localhost:3000">
                        <p class="description">URL where your external Node.js bot is running.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="bot_username">WordPress Username for Bot</label></th>
                    <td>
                        <input name="bot_username" type="text" id="bot_username" value="<?php echo esc_attr($bot_username); ?>" class="regular-text" required >
                        <p class="description">An administrator or editor WP account username.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="bot_password">WordPress Application Password</label></th>
                    <td>
                        <input name="bot_password" type="password" id="bot_password" value="<?php echo esc_attr($bot_password); ?>" class="regular-text" required >
                        <p class="description">The 24-character Application Password generated for the specific WP Username.</p>
                    </td>
                </tr>
            </table>
            <p class="submit">
                <input type="submit" name="wp_bot_submit" id="submit" class="button button-primary" value="Save Settings & Connect">
            </p>
        </form>

        <hr>
        
        <h2>Bot Post History</h2>
        <p>Posts below were generated automatically via your Telegram Bot connection.</p>
        <table class="wp-list-table widefat fixed striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Date Created</th>
                    <th>Visibility Status</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $args = array(
                    'post_type' => 'post',
                    'post_status' => 'any',
                    'meta_query' => array(
                        array(
                            'key' => '_created_by_bot',
                            'value' => '1',
                            'compare' => '='
                        )
                    )
                );
                
                $bot_posts = new WP_Query($args);
                
                if ($bot_posts->have_posts()) {
                    while ($bot_posts->have_posts()) {
                        $bot_posts->the_post();
                        echo '<tr>';
                        echo '<td><strong><a href="' . get_edit_post_link() . '">' . get_the_title() . '</a></strong></td>';
                        echo '<td>' . get_the_date() . ' at ' . get_the_time() . '</td>';
                        echo '<td>' . get_post_status() . '</td>';
                        echo '</tr>';
                    }
                    wp_reset_postdata();
                } else {
                    echo '<tr><td colspan="3">No posts explicitly created by the bot are currently available.</td></tr>';
                }
                ?>
            </tbody>
        </table>
    </div>
    <?php
}
